/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const RouteSelectionIndexLazyImport = createFileRoute('/route-selection/')()
const PurchaseIndexLazyImport = createFileRoute('/purchase/')()
const ProfileIndexLazyImport = createFileRoute('/profile/')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RouteSelectionIndexLazyRoute = RouteSelectionIndexLazyImport.update({
  path: '/route-selection/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/route-selection/index.lazy').then((d) => d.Route),
)

const PurchaseIndexLazyRoute = PurchaseIndexLazyImport.update({
  path: '/purchase/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/purchase/index.lazy').then((d) => d.Route),
)

const ProfileIndexLazyRoute = ProfileIndexLazyImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/purchase/': {
      id: '/purchase/'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/route-selection/': {
      id: '/route-selection/'
      path: '/route-selection'
      fullPath: '/route-selection'
      preLoaderRoute: typeof RouteSelectionIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ProfileIndexLazyRoute,
  PurchaseIndexLazyRoute,
  RouteSelectionIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile/",
        "/purchase/",
        "/route-selection/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.lazy.tsx"
    },
    "/purchase/": {
      "filePath": "purchase/index.lazy.tsx"
    },
    "/route-selection/": {
      "filePath": "route-selection/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
