/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './renderer/src/routes/__root'

// Create Virtual Routes

const PurchaseIndexLazyImport = createFileRoute('/purchase/')()
const ProfileIndexLazyImport = createFileRoute('/profile/')()
const IndexIndexLazyImport = createFileRoute('/index/')()

// Create/Update Routes

const PurchaseIndexLazyRoute = PurchaseIndexLazyImport.update({
  path: '/purchase/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./renderer/src/routes/purchase/index.lazy').then((d) => d.Route),
)

const ProfileIndexLazyRoute = ProfileIndexLazyImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./renderer/src/routes/profile/index.lazy').then((d) => d.Route),
)

const IndexIndexLazyRoute = IndexIndexLazyImport.update({
  path: '/index/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./renderer/src/routes/index/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index/': {
      id: '/index/'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof IndexIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/purchase/': {
      id: '/purchase/'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexIndexLazyRoute,
  ProfileIndexLazyRoute,
  PurchaseIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/index/",
        "/profile/",
        "/purchase/"
      ]
    },
    "/index/": {
      "filePath": "index/index.lazy.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.lazy.tsx"
    },
    "/purchase/": {
      "filePath": "purchase/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
